#server.port=8001
#
#eureka.instance.hostname=eureka01
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone=http://localhost:8001/eureka/



server:
  port: 8080
eureka:
  instance:
    hostname: eureka01
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8081/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-service