

server:
  port: 8081
eureka:
  instance:
    hostname: eureka02
  client:
#    fetch-registry: false
#    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-service